### ISSUE TITLE
Vertical Free Rows Space

### ISSUE THREAD

**Issue by toleabivol** [ncthis/gridster-bootstrap#7]
When gridster is set to :

    shift_widgets_up: false, //sticky widgets (place anywhere)

We can create blank rows. When serializing via gridster-bootstrap these are ignored.

**Comment by nadeesha** [comment]
Sorry, the current implementation does not support blank rows.

Also, I'm deprecating the library because the problem it tries to solve is better solved by [Gridstack](http://troolee.github.io/gridstack.js/).
